name: Noir

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Noir toolchain
      uses: noir-lang/noirup@v0.1.3
      with:
        toolchain: nightly
    - name: Run Poseidon string hashing tests
      run: |
        cd noir-examples/poseidon-hash-long-strings
        nargo test
    - name: Prove and verify certificate verification circuit for addresses
      run: |
        cd noir-examples/verify_human_certificates_for_address
        nargo prove
        nargo verify
    - name: Prove and verify certificate verification circuit for public keys
      run: |
        cd noir-examples/verify_human_certificates_for_public_key
        nargo prove
        nargo verify
