name: Noir

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Noir toolchain
      uses: noir-lang/noirup@v0.1.3
      with:
        toolchain: nightly
    - name: Run Poseidon string hashing tests
      run: |
        cd noir-examples/poseidon-hash-long-strings
        nargo test
    - name: Prove certificate verification circuit
      run: |
        cd noir-examples/verify_certificates
        nargo prove
    - name: Verify certificate verification circuit
      run: |
        cd noir-examples/verify_certificates
        nargo verify
